set(_CATKIN_CURRENT_PACKAGE "pb_msgs_example")
set(pb_msgs_example_VERSION "1.0.0")
set(pb_msgs_example_MAINTAINER "Apollo Authors <info@apollo.auto>")
set(pb_msgs_example_PACKAGE_FORMAT "1")
set(pb_msgs_example_BUILD_DEPENDS "roscpp" "gencpp" "genmsg" "genpy" "std_msgs" "pb_msgs")
set(pb_msgs_example_BUILD_EXPORT_DEPENDS "roscpp" "gencpp" "genmsg" "genpy" "std_msgs" "pb_msgs")
set(pb_msgs_example_BUILDTOOL_DEPENDS "catkin")
set(pb_msgs_example_BUILDTOOL_EXPORT_DEPENDS )
set(pb_msgs_example_EXEC_DEPENDS "roscpp" "gencpp" "genmsg" "genpy" "std_msgs" "pb_msgs")
set(pb_msgs_example_RUN_DEPENDS "roscpp" "gencpp" "genmsg" "genpy" "std_msgs" "pb_msgs")
set(pb_msgs_example_TEST_DEPENDS )
set(pb_msgs_example_DOC_DEPENDS )
set(pb_msgs_example_DEPRECATED "")